# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('description', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.User')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserPrefGame',
            fields=[
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.Preference')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='user.Game')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='preferences',
            field=models.ManyToManyField(through='user.UserPrefGame', to='user.Preference'),
        ),
    ]
